//CLIENT
const ALL_CLIENT     = '@client/ALL'
const FILTER_CLIENTS = '@client/FILTER'
const UPDATE_CLIENT  = '@client/UPDATE'

//COLLABORATOR

//SALON

//SCHEDULE

//SCHEDULING
const ALL_SCHEDULING    = '@scheduling/ALL'
const FILTER_SCHEDULING = '@scheduling/FILTER'
const UPDATE_SCHEDULING = '@scheduling/UPDATE'

//SERVICE


export {

    ALL_CLIENT,
    FILTER_CLIENTS,
    UPDATE_CLIENT,

    ALL_SCHEDULING,
    FILTER_SCHEDULING,
    UPDATE_SCHEDULING,

}
