//CLIENT
const CLIENT_ALL    = '@client/ALL'
const CLIENT_FILTER = '@client/FILTER'
const CLIENT_UPDATE = '@client/UPDATE'

//COLLABORATOR

//SALON

//SCHEDULE

//SCHEDULING
const SCHEDULING_ALL    = '@scheduling/ALL'
const SCHEDULING_FILTER = '@scheduling/FILTER'
const SCHEDULING_UPDATE = '@scheduling/UPDATE'

//SERVICE


export {

    CLIENT_ALL,
    CLIENT_FILTER,
    CLIENT_UPDATE,

    SCHEDULING_ALL,
    SCHEDULING_FILTER,
    SCHEDULING_UPDATE,

}
